dist: bionic
language: python
cache: pip
python:
- '3.7'
stages:
- test
- name: pypi
  if: tag IS present
install:
- pip3 install poetry
- poetry install
jobs:
  include:
  - stage: test
    script:
    - poetry run pytest --cov-report xml --cov apubsub
    - bash <(curl -s https://codecov.io/bash)
  - stage: pypi
    name: Deploy to PyPi
    script: poetry publish --build -u $PYPI_USERNAME -p $PYPI_PASSWORD
