dist: bionic
language: python
cache: pip
python:
- '3.7'
stages:
- test
- name: pypi
  if: tag IS present
install:
- pip3 install poetry
- poetry install
jobs:
  include:
  - stage: test
    script: poetry run pytest --cov psub
  - stage: pypi
    name: Deploy to PyPi
    script: poetry publish --build -u $PYPI_USERNAME -p $PYPI_PASSWORD
env:
  global:
  - secure: rU5bvkQSd4GrWXzbv2emcR+C5wFi0ZPl3VSgI0Zmf4ZmcqMaLojEFt3GmHkr+X382R60oungcn17E2ws7AOn9T78TB/aCz5C9iFbc757XIjjBzcepvO56GNmtLZHZkl0Q7K3eSFOzoBdn32msBG8AMdcA9bWUKbTVSW882MuoDMpTAOvh9xKZ5b293b9YXUlXBl8FuQfsteJ0ztdC+N3VrJ3zB1yUj+oe2vnFl7ghgfM8eRBtp8dhCxXOKpVNkq+jleqwf8qfaMUzNDgW2M9p/j9OMzygW3uERNhCCO4s7zwrs1r6khfA5oh8EffGYS6Rxi8aYorGtmEVH2xULbKCu7J2/N5CinJCzjPbW48oL0Y8yyhIYWiJcIk+DaKBGz0h3OYdgmhSdZZOppVZjkUb6QBNY431UzrNUtkqEcrcUdUaMIiiq42XjpK1ZWNho8BQqnnuxm8IapvQ666594h5Vixy3yEUVmcyKRMSHv3J4UXNuux8ePJoirh5BbGvRM5lCVMiwbCZXCpGB4Ids0zYw9XPuRolrojf7SGSG686SqADImxIJnq6c8UI/L3hZzitKFoMy4iXRh8KNABpyMlxab+8AwOkL18phay57f/ze2hlngF/m/VYU5EUA0c1uPgRf29Y+pDDRPifyzCjeQQ+c7GHHTxgeIxJDJrcGzFLGE=
  - secure: CkRLw3BEgzD3Db2zndZ3hkWtTRyZIfqbexeuQbBX+IqrWenq451c4kEysUEhrBLykEu/5ifSYTUu/qME2G1Nwn50Pz31G91o2WjHEUsTy0kehooZOww0WFr5pOzljZfAK9nF2Dv1mu0D2kkH+1ZlPid2iG3YdlY2/amEgBL90csTDd4IHkOcqEU02EhJvdQ3OjKsE6iZ3uI83uNRyMFVHEokN8FVYrfSDkv+1eTjUZ3Ml3zJJFdY3MyHOOIpCQ989geAccgzvyBiJnEHqaWrFyVm7L7KJlNNdVB9jkxRQATCZsagzZrJMCCgqO0jfkqvyzZOXX4Jwr2Lq8VK822rM3++Bc8eK8/DEiywWlRw2DpBkBlDlPUy/uaHt4htP/YGX5jvugqPsrq1k6k3CbS/T+cXS7t8LwniFHQ/OqrSKMf0y9mVZ2mGkwFb176AsD2WSjPu6DL05i0PlTLqSvfr+SyNwZADE2P73Vvxw7oQnLtJF7DS856a3X/Id5/veCjTA6iefTb3kayKGbTNfLPtq8dwRdvd87UruwOafifNiKO8RUJY28w+29pWwVteVRfpBuLe3XUbOHAshzlzXVH3PwT3p3jOHkp4I+K98EL3BuzcUcuWU7Ybf3nlX3HKyzXjYnoU+aXMtAAsyA+mM/WcQNNMU7Iyy1poNIeph8GIwDQ=
