dist: bionic
language: python
cache: pip
python:
- '3.7'
stages:
- test
- report
- name: pypi
  if: tag IS present
install:
- pip3 install poetry
- poetry install
jobs:
  include:
  - stage: test
    script: poetry run pytest --cov-report xml --cov apubsub
  - stage: report
    script: poetry run codecov
  - stage: pypi
    name: Deploy to PyPi
    script: poetry publish --build -u $PYPI_USERNAME -p $PYPI_PASSWORD
env:
  global:
  - secure: rU5bvkQSd4GrWXzbv2emcR+C5wFi0ZPl3VSgI0Zmf4ZmcqMaLojEFt3GmHkr+X382R60oungcn17E2ws7AOn9T78TB/aCz5C9iFbc757XIjjBzcepvO56GNmtLZHZkl0Q7K3eSFOzoBdn32msBG8AMdcA9bWUKbTVSW882MuoDMpTAOvh9xKZ5b293b9YXUlXBl8FuQfsteJ0ztdC+N3VrJ3zB1yUj+oe2vnFl7ghgfM8eRBtp8dhCxXOKpVNkq+jleqwf8qfaMUzNDgW2M9p/j9OMzygW3uERNhCCO4s7zwrs1r6khfA5oh8EffGYS6Rxi8aYorGtmEVH2xULbKCu7J2/N5CinJCzjPbW48oL0Y8yyhIYWiJcIk+DaKBGz0h3OYdgmhSdZZOppVZjkUb6QBNY431UzrNUtkqEcrcUdUaMIiiq42XjpK1ZWNho8BQqnnuxm8IapvQ666594h5Vixy3yEUVmcyKRMSHv3J4UXNuux8ePJoirh5BbGvRM5lCVMiwbCZXCpGB4Ids0zYw9XPuRolrojf7SGSG686SqADImxIJnq6c8UI/L3hZzitKFoMy4iXRh8KNABpyMlxab+8AwOkL18phay57f/ze2hlngF/m/VYU5EUA0c1uPgRf29Y+pDDRPifyzCjeQQ+c7GHHTxgeIxJDJrcGzFLGE=
  - secure: CkRLw3BEgzD3Db2zndZ3hkWtTRyZIfqbexeuQbBX+IqrWenq451c4kEysUEhrBLykEu/5ifSYTUu/qME2G1Nwn50Pz31G91o2WjHEUsTy0kehooZOww0WFr5pOzljZfAK9nF2Dv1mu0D2kkH+1ZlPid2iG3YdlY2/amEgBL90csTDd4IHkOcqEU02EhJvdQ3OjKsE6iZ3uI83uNRyMFVHEokN8FVYrfSDkv+1eTjUZ3Ml3zJJFdY3MyHOOIpCQ989geAccgzvyBiJnEHqaWrFyVm7L7KJlNNdVB9jkxRQATCZsagzZrJMCCgqO0jfkqvyzZOXX4Jwr2Lq8VK822rM3++Bc8eK8/DEiywWlRw2DpBkBlDlPUy/uaHt4htP/YGX5jvugqPsrq1k6k3CbS/T+cXS7t8LwniFHQ/OqrSKMf0y9mVZ2mGkwFb176AsD2WSjPu6DL05i0PlTLqSvfr+SyNwZADE2P73Vvxw7oQnLtJF7DS856a3X/Id5/veCjTA6iefTb3kayKGbTNfLPtq8dwRdvd87UruwOafifNiKO8RUJY28w+29pWwVteVRfpBuLe3XUbOHAshzlzXVH3PwT3p3jOHkp4I+K98EL3BuzcUcuWU7Ybf3nlX3HKyzXjYnoU+aXMtAAsyA+mM/WcQNNMU7Iyy1poNIeph8GIwDQ=
  - secure: q3iFzmwQHoIEox42T7ShtvbOKQV6ZdzsV2BDSUzti2O08uCmod/b8GkOddyXFM1OuOVXRufAzYhlk+2iOQmO3KQlx9vS6L8vBXaNfrg3lc7EkxLD7/0oDI83yUH/Dqal8dZgvSd50IWcVdsTsDLy/g6oAkxjnzkILGCKmpJyR6F3ezJHANF5SU1/T1qwjOm7vNopMI05dVpZ4k5llRR4iYyncJmLb13jC5TvP27uWjiFTKMK4xXaHOi55AUrSng3iUY4S2JS2f3tByHI/mL09N95lZqxyEKQdyeM3UXI7fbxI0xYPs22esneFjwtbdXygl8RytHumWTMizb6q0VgpsNqiA9D7YiJxbcCJz3cN8PuXpCevJZwOQ8nmAwp3UbnSqv/5Z4eOkcT0RUVhRG9majjVtWxaQVx2laFL+vvBV5X6qJFAL44HGWxvdGcTQlYFXZWuKKW5wx9vK5GzkQ31KB+y3RBA4E9gIKS/BNhojQ4CSCu2cekqBSex7c2GfrQ5YOA8zhOs02AbipeoPhihUgUHgFj37g4/fU1JsoBv4i40SnVdW4Is1fVuDqhkiO/TcWOfHgFVOihFMTHqG7ZtSkbW4q5heZHoOvtV0u1wbynBc39XKGFeOCDVmgSoLdWu2/XMbjB9uk28h4svZr0glloRs/SY8usRUdRJEAbBns=
